### ISSUE TITLE
Wrong account being selected

### ISSUE THREAD

**Issue by lwatsondev** [andykais/bitwarden-dmenu#5]
Now that #4 works, when I select certain accounts, `Rizon: Leliana` for example, it actually returns the password for `Paypal: <my@email.address>`. I've had a poke around and I *think* it's something to do with https://github.com/andykais/bitwarden-dmenu/blob/master/src/index.js#L61 being passed as an array key to an array where the keys are `['accountname']` instead of `['accountname: username']`. The part I have no idea about is why some work fine and others don't even though they all do the same array indexing.

**Comment by andykais** [comment]
ah I see now! So the list of logins, cards and identities (`list`) was getting filtered down to just logins for dmenu (`accountNames`), the length of `accountNames` did not match `list` so the index of the selected `accountNames` string was not the correct index

Fixed in https://github.com/andykais/bitwarden-dmenu/commit/8804c65df90a08fd44545ffa70df30ae793ce431 and `bitwarden-dmenu@1.2.4`

**Comment by lwatsondev** [comment]
Works great :)
